services:
  - type: web
    region: singapore
    name: alexdrive-backend
    runtime: docker
    dockerfilePath: ./alexdrivebackend/Dockerfile
    dockerContext: ./alexdrivebackend
    plan: starter
    healthCheckPath: /api/health
    envVars:
      - key: SOURCE_BASE_URL
        sync: false
      - key: PROXY_URL
        sync: false
      - key: CORS_ORIGINS
        sync: false

  - type: web
    region: singapore
    name: alexdrive-frontend
    runtime: docker
    dockerfilePath: ./alexdriveapp/Dockerfile
    dockerContext: ./alexdriveapp
    plan: starter
    envVars:
      - key: BACKEND_URL
        sync: false
      - key: NEXT_PUBLIC_BACKEND_URL
        sync: false
